### ISSUE TITLE
2.2.5 fails to build: class ObjCryst::UnitCell’ has no member named ‘ChangeSpaceGroup’

### ISSUE THREAD

**Issue by stefanor** [diffpy/pyobjcryst#37]
I tried updating to 2.2.5 in Debian, and got a build failure, that doesn't look related to anything Debian-specific:

```
g++ -o build/debug-3.11/unitcell_ext.os -c -DBOOST_ERROR_CODE_HEADER_ONLY -std=c++11 -Wsign-compare -fstack-protector-strong -Wformat -Werror=format-security -fwrapv -Wall -fno-strict-aliasing -g -fPIC -DBOOST_ERROR_CODE_HEADER_ONLY -I/usr/include/python3.11 -Ibuild/debug-3.11/debian/pyobjcryst/include -I/usr/lib/python3/dist-packages/numpy/core/include build/debug-3.11/unitcell_ext.cpp
build/debug-3.11/unitcell_ext.cpp: In function ‘void {anonymous}::SafeChangeSpaceGroup(ObjCryst::UnitCell&, const std::string&)’:
build/debug-3.11/unitcell_ext.cpp:143:7: error: ‘class ObjCryst::UnitCell’ has no member named ‘ChangeSpaceGroup’; did you mean ‘GetSpaceGroup’?
  143 |     u.ChangeSpaceGroup(sgid);
      |       ^~~~~~~~~~~~~~~~
      |       GetSpaceGroup
```

**Comment by vincefn** [comment]
Have you also updated `libobjcryst` ? This was added in 2022.1.4, so `pyobjcryst` 2.2.5 depends on it:
https://github.com/diffpy/libobjcryst/blob/master/CHANGELOG.md

Since the debian packages are stuck right now (from wht I see in https://tracker.debian.org/pkg/libobjcryst), the easiest way may be to install via conda.

**Comment by stefanor** [comment]
Oh, duh. Nevermind :)
Sorry, I don't usually touch this package, so  I'm not exactly familiar with it. I assumed this was something wrong internally.
