### ISSUE TITLE
Support for Python 3.7

### ISSUE THREAD

**Issue by Sparks29032** [diffpy/pyobjcryst#40]
Is it possible to include support for Python 3.7 to be compatible with diffpy-cmi? Also, will there be a pypi release of version 2024.1.1?

**Comment by vincefn** [comment]
Python 3.7 is EOL since this summer, and it was removed from conda-forge builds even before that I think. So I'm not sure I can do anything about that.

As for pypi, I spent some time a while ago trying to figure what is wrong but finally gave up. I do welcome any contribution to find what is wrong there, but I don't really ahve time to spend on this as I have no use for it. Are you using it ?

**Comment by Sparks29032** [comment]
We were hoping pypi would ignore versioning. Is it possible to make the `.ci_support` files independent of python version (such as those in the `.ci_support` of `libobjcryst-feedstock`)?

**Comment by vincefn** [comment]
pip install should work, e.g. I tried successfully the following recipe under linux:

``` bash
mamba create -n py37 python=3.7 numpy packaging scons boost
mamba activate py37
curl -LO https://github.com/diffpy/libobjcryst/archive/refs/tags/v2024.1.1.tar.gz
tar -xzf v2024.1.1.tar.gz 
cd libobjcryst-2024.1.1/
scons -j4 install
cd ..
rm -f v2024.1.1.tar.gz 
curl -LO https://github.com/diffpy/pyobjcryst/archive/refs/tags/v2024.1.1.tar.gz
tar -xzf v2024.1.1.tar.gz 
cd pyobjcryst-2024.1.1/
CPLUS_INCLUDE_PATH=$CONDA_PREFIX/include LIBRARY_PATH=$CONDA_PREFIX/lib pip install .
```

Not sure if trying to add 3.7 to the conda build would work (not a conda-forge expert), or if it is a good idea (it's past its EOL).

**Comment by vincefn** [comment]
> We were hoping pypi would ignore versioning. Is it possible to make the `.ci_support` files independent of python version (such as those in the `.ci_support` of `libobjcryst-feedstock`)?

`libobjcryst` is pure C++, no python, so no reason to depend on python.

For `pyobjcryst` I don't think it would be possible, since `boost-python-devel` it depends on is pinned on python versions.

Let me know if the above script works - environment variables for the final pip install may need to be adapted depending on the OS.

**Comment by sbillinge** [comment]
We will also work on updating diffpy-cmi.... But not sure what we will find
yet.

**Comment by Sparks29032** [comment]
> `libobjcryst` is pure C++, no python, so no reason to depend on python.
> For `pyobjcryst` I don't think it would be possible, since boost-python-devel it depends on is pinned on python versions.

Makes sense.

> Let me know if the above script works

Install worked on `Python 3.7` without `diffpy-cmi`, substituted final `pip` install for `scons`. No errors when running code from #39. However `libobjcryst` does not display on `conda list`. Then, installing diffpy-cmi on top of this installation causes a conflicting `libobjcryst` install. We cannot install the components individually either as `diffpy.srreal` requires `libdiffpy` which comes with a conflicting install of `libobjcryst`. There are also conflicting installs with the `boost` version: `pyobjcryst` with 1.80.0 and `libdiffpy` less than 1.68.*.

**Comment by vincefn** [comment]
Can you try installing `libobjcryst` 2024.1.1 using conda (so it is listed in conda), then only `pyobjcryst` using `pip/scons` ?

> We will also work on updating diffpy-cmi.... But not sure what we will find yet.

Could be good to move it to conda-forge so it gets more regularly rebuilt.

**Comment by Sparks29032** [comment]
We did install `libobjcryst=2024.1.1` with conda, but that resulted in the conflicting install error when installing `libdiffpy`.

**Comment by vincefn** [comment]
Note that you shouldn't actually _need_ `libobjcryst` `2024.1.1` for `pyobjcryst` `2024.1.1`- the requirement is made in conda only because it is better to rely on the latest `libobjcryst` (which fixes the segfault when you have some molecule atoms without any bond).

But if you install `pyobjcryst` via pip/scons you could simply use an older (well, not _too_ old) version of `libobjcryst` and it should work. What you really need from what I understand is the MolZAtom python representation, which is pure `pyobjcryst`.

**Comment by carltta** [comment]
We tried many different combinations, also `libobjcryst` `2017.2.2` (which is the version automatically installed with `diffpy`) with `pyobjcryst` `2024.1.1` and the `diffpy` package but then the code to get the ZMatrix doesn't work anymore. I got the following error:

ImportError: /anaconda3/envs/py37/lib/python3.7/site-packages/pyobjcryst-2024.1.1-py3.7-linux-x86_64.egg/pyobjcryst/_pyobjcryst.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN8ObjCryst19ZScatterer2MoleculeEPNS_10ZScattererE

We don't know what we could still try.

Actually we would like to use MolZAtom together with `diffpy.srreal`.

**Comment by vincefn** [comment]
I'm out of ideas - since diffpy (and notably `srreal`) is C++-compiled against `libobjcryst`, I don't see how you can avoid problems without recompiling everything from source. There's just too much difference since the 2017 version.

**Comment by sbillinge** [comment]
Thanks Vincent, we'll work on updating cmi.  We wanted to get pdfgui
updated first, but that work is now done, bar some testing.

**Comment by vincefn** [comment]
I'd suggest to close this - now we're closing onto the python _3.8_ end-of-life (3.13 is almost here),, so... I hope it's now OK in diffpy.
